server:
  port: 16115
  additionalPorts: 17001,16108,16101

spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDRS:nacos-0.nacos-headless.default.svc.cluster.local,nacos-1.nacos-headless.default.svc.cluster.local,nacos-2.nacos-headless.default.svc.cluster.local}
  application:
    name: ts-united-monolith
  mail:
    host: smtp.163.com
    port: 465
    username: ${email_address:trainticket_notify@163.com}
    password: ${email_password:GZKSCXHBOLKMCLDQ}
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          auth: true
          starttls:
            enable: true
            required: true
  datasource:
    url: jdbc:mysql://${UNITED_MONOLITH_MYSQL_HOST:ts-united-monolith-mysql}:${UNITED_MONOLITH_MYSQL_PORT:3306}/${UNITED_MONOLITH_MYSQL_DATABASE:ts-united-monolith-mysql}?useSSL=false
    username: ${UNITED_MONOLITH_MYSQL_USER:root}
    password: ${UNITED_MONOLITH_MYSQL_PASSWORD:Abcd1234#}
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: ${rabbitmq_host:localhost}
    port: 5672
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

swagger:
  controllerPackage: unitedmonolith.controller