# HTTP Server
server:
  port: 16101  # HTTP (Tomcat) port

spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDRS:127.0.0.1:8848}
  application:
    name: ts-voucher-service
  datasource:
    url: jdbc:mysql://${VOUCHER_MYSQL_HOST:10.176.122.1}:${VOUCHER_MYSQL_PORT:3306}/${VOUCHER_MYSQL_DATABASE:ts}?useSSL=false
    username: ${VOUCHER_MYSQL_USER:root}
    password: ${VOUCHER_MYSQL_PASSWORD:Abcd1234#}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

swagger:
  controllerPackage: voucher.controller